---
title: "SVM_modeling"
format: html
---

## load packages
```{r}
library(e1071)
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyverse) 
library(tidymodels) #Modeling
library(ranger)
library(probably)
library(vip)
library(yardstick)
library(rpart.plot)
library(caret)
```

## load datasets
```{r}
csf <- read.csv("C:/Users/new account/Desktop/NACC_data/original_data/data_cleaned/csf.csv")
mri <- read.csv("C:/Users/new account/Desktop/NACC_data/original_data/data_cleaned/mri.csv")
uds <- read.csv("C:/Users/new account/Desktop/NACC_data/original_data/data_cleaned/uds.csv")

df_list <- list(uds, csf)
masterset <- df_list |> reduce(full_join, by="NACCID")

# select predictors
predictors_df <- masterset %>% 
  select(SEX,
          EDUC,
          NACCAGE,
          VEG,
          ANIMALS,
          TRAILA,
          TRAILB,
          CRAFTDRE,
          MINTTOTS,
          MEMPROB,
          DROPACT,
          WRTHLESS,
          BETTER,
          BORED,
          HELPLESS,
          TAXES,
          BILLS,
          REMDATES,
          TRAVEL,
          NACCUDSD,
          MEALPREP,
          GAMES) %>%
  mutate(across(c(SEX,
                  MEMPROB,
                  DROPACT,
                  WRTHLESS,
                  BETTER,
                  BORED,
                  HELPLESS,
                  TAXES,
                  BILLS,
                  REMDATES,
                  TRAVEL,
                  MEALPREP,
                  GAMES), as.factor))



#create 2 separate datasets: HC and Not HC; MCI and AD

HC_notHC_set <- predictors_df |>
  filter(NACCUDSD == "1" | NACCUDSD == "3" | NACCUDSD == "4") |>
  mutate(cog_stat = case_when(NACCUDSD == 1 ~ "HC",
                              NACCUDSD == 3 ~ "Not HC",
                              NACCUDSD == 4 ~ "Not HC")) |>
  select(-NACCUDSD) |> na.omit()
MCI_AD_set <- predictors_df |>
  filter(NACCUDSD == "3" | NACCUDSD == "4") |>
  mutate(cog_stat = case_when(NACCUDSD == 3 ~ "MCI",
                              NACCUDSD == 4 ~ "AD")) |>
  select(-NACCUDSD) |> na.omit()


# training and test set for HC_notHC_set
set.seed(777)
HC_notHC_split <- initial_split(HC_notHC_set, prop = 0.8)
HC_notHC_train <- training(HC_notHC_split)
HC_notHC_test <- testing(HC_notHC_split)

# training and test set for MCI_AD_set
set.seed(777)
MCI_AD_split <- initial_split(MCI_AD_set, prop = 0.8)
MCI_AD_train <- training(MCI_AD_split)
MCI_AD_test <- testing(MCI_AD_split)
```

## SVM for HC_notHC_set
response variable: cog_stat
```{r}
svmfit1 <- svm(factor(cog_stat) ~ ., data = HC_notHC_train, kernel = "linear", cost = 10, cross = 10)
summary(svmfit1)

pred1 <- predict(svmfit1, HC_notHC_test)
plot(pred1)
table(pred1, HC_notHC_test$cog_stat)
```

## SVM for MCI_AD_set
```{r}
svmfit2 <- svm(factor(cog_stat) ~ ., data = MCI_AD_train, kernel = "linear", cost = 10, cross = 10)
summary(svmfit2)

pred2 <- predict(svmfit2, MCI_AD_test)
plot(pred2)
table(pred2, MCI_AD_test$cog_stat)
```

